// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

using PutridParrot.UnitsApi.Resources;
using PutridParrot.Units;

namespace PutridParrot.UnitsApi.Converters
{
	public partial class AngleConverters
	{
		public AngleConverters()
		{
			Converters = new Dictionary<string, Dictionary<string, Func<double, double>>>
			{
				{
					AppResources.Degrees, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Radians, Angle.Degrees.ToRadians },
						{ AppResources.Gradians, Angle.Degrees.ToGradians },
						{ AppResources.Milliradians, Angle.Degrees.ToMilliradians },
						{ AppResources.MinuteOfArc, Angle.Degrees.ToMinuteOfArc },
						{ AppResources.SecondsOfArc, Angle.Degrees.ToSecondsOfArc },
					}
				},
				{
					AppResources.Gradians, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Degrees, Angle.Gradians.ToDegrees },
						{ AppResources.Radians, Angle.Gradians.ToRadians },
						{ AppResources.Milliradians, Angle.Gradians.ToMilliradians },
						{ AppResources.MinuteOfArc, Angle.Gradians.ToMinuteOfArc },
						{ AppResources.SecondsOfArc, Angle.Gradians.ToSecondsOfArc },
					}
				},
				{
					AppResources.Milliradians, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Degrees, Angle.Milliradians.ToDegrees },
						{ AppResources.Radians, Angle.Milliradians.ToRadians },
						{ AppResources.Gradians, Angle.Milliradians.ToGradians },
						{ AppResources.MinuteOfArc, Angle.Milliradians.ToMinuteOfArc },
						{ AppResources.SecondsOfArc, Angle.Milliradians.ToSecondsOfArc },
					}
				},
				{
					AppResources.MinuteOfArc, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Degrees, Angle.MinuteOfArc.ToDegrees },
						{ AppResources.Radians, Angle.MinuteOfArc.ToRadians },
						{ AppResources.Gradians, Angle.MinuteOfArc.ToGradians },
						{ AppResources.Milliradians, Angle.MinuteOfArc.ToMilliradians },
						{ AppResources.SecondsOfArc, Angle.MinuteOfArc.ToSecondsOfArc },
					}
				},
				{
					AppResources.Radians, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Degrees, Angle.Radians.ToDegrees },
						{ AppResources.Gradians, Angle.Radians.ToGradians },
						{ AppResources.Milliradians, Angle.Radians.ToMilliradians },
						{ AppResources.MinuteOfArc, Angle.Radians.ToMinuteOfArc },
						{ AppResources.SecondsOfArc, Angle.Radians.ToSecondsOfArc },
					}
				},
				{
					AppResources.SecondsOfArc, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Degrees, Angle.SecondsOfArc.ToDegrees },
						{ AppResources.Radians, Angle.SecondsOfArc.ToRadians },
						{ AppResources.Gradians, Angle.SecondsOfArc.ToGradians },
						{ AppResources.Milliradians, Angle.SecondsOfArc.ToMilliradians },
						{ AppResources.MinuteOfArc, Angle.SecondsOfArc.ToMinuteOfArc },
					}
				}
			};
		}

		public Dictionary<string, Dictionary<string, Func<double, double>>> Converters { get; }
	}
}
