// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

using PutridParrot.UnitsApi.Resources;
using PutridParrot.Units;

namespace PutridParrot.UnitsApi.Converters
{
	public partial class AreaConverters
	{
		public AreaConverters()
		{
			Converters = new Dictionary<string, Dictionary<string, Func<double, double>>>
			{
				{
					AppResources.Acres, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.SquareKilometres, Area.Acres.ToSquareKilometres },
						{ AppResources.SquareMetres, Area.Acres.ToSquareMetres },
						{ AppResources.SquareMiles, Area.Acres.ToSquareMiles },
						{ AppResources.SquareYards, Area.Acres.ToSquareYards },
						{ AppResources.SquareFeet, Area.Acres.ToSquareFeet },
						{ AppResources.SquareInches, Area.Acres.ToSquareInches },
						{ AppResources.Hectares, Area.Acres.ToHectares },
					}
				},
				{
					AppResources.Hectares, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.SquareKilometres, Area.Hectares.ToSquareKilometres },
						{ AppResources.SquareMetres, Area.Hectares.ToSquareMetres },
						{ AppResources.SquareMiles, Area.Hectares.ToSquareMiles },
						{ AppResources.SquareYards, Area.Hectares.ToSquareYards },
						{ AppResources.SquareFeet, Area.Hectares.ToSquareFeet },
						{ AppResources.SquareInches, Area.Hectares.ToSquareInches },
						{ AppResources.Acres, Area.Hectares.ToAcres },
					}
				},
				{
					AppResources.SquareFeet, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.SquareKilometres, Area.SquareFeet.ToSquareKilometres },
						{ AppResources.SquareMetres, Area.SquareFeet.ToSquareMetres },
						{ AppResources.SquareMiles, Area.SquareFeet.ToSquareMiles },
						{ AppResources.SquareYards, Area.SquareFeet.ToSquareYards },
						{ AppResources.SquareInches, Area.SquareFeet.ToSquareInches },
						{ AppResources.Hectares, Area.SquareFeet.ToHectares },
						{ AppResources.Acres, Area.SquareFeet.ToAcres },
					}
				},
				{
					AppResources.SquareInches, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.SquareKilometres, Area.SquareInches.ToSquareKilometres },
						{ AppResources.SquareMetres, Area.SquareInches.ToSquareMetres },
						{ AppResources.SquareMiles, Area.SquareInches.ToSquareMiles },
						{ AppResources.SquareYards, Area.SquareInches.ToSquareYards },
						{ AppResources.SquareFeet, Area.SquareInches.ToSquareFeet },
						{ AppResources.Hectares, Area.SquareInches.ToHectares },
						{ AppResources.Acres, Area.SquareInches.ToAcres },
					}
				},
				{
					AppResources.SquareKilometres, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.SquareMetres, Area.SquareKilometres.ToSquareMetres },
						{ AppResources.SquareMiles, Area.SquareKilometres.ToSquareMiles },
						{ AppResources.SquareYards, Area.SquareKilometres.ToSquareYards },
						{ AppResources.SquareFeet, Area.SquareKilometres.ToSquareFeet },
						{ AppResources.SquareInches, Area.SquareKilometres.ToSquareInches },
						{ AppResources.Hectares, Area.SquareKilometres.ToHectares },
						{ AppResources.Acres, Area.SquareKilometres.ToAcres },
					}
				},
				{
					AppResources.SquareMetres, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.SquareKilometres, Area.SquareMetres.ToSquareKilometres },
						{ AppResources.SquareMiles, Area.SquareMetres.ToSquareMiles },
						{ AppResources.SquareYards, Area.SquareMetres.ToSquareYards },
						{ AppResources.SquareFeet, Area.SquareMetres.ToSquareFeet },
						{ AppResources.SquareInches, Area.SquareMetres.ToSquareInches },
						{ AppResources.Hectares, Area.SquareMetres.ToHectares },
						{ AppResources.Acres, Area.SquareMetres.ToAcres },
					}
				},
				{
					AppResources.SquareMiles, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.SquareKilometres, Area.SquareMiles.ToSquareKilometres },
						{ AppResources.SquareMetres, Area.SquareMiles.ToSquareMetres },
						{ AppResources.SquareYards, Area.SquareMiles.ToSquareYards },
						{ AppResources.SquareFeet, Area.SquareMiles.ToSquareFeet },
						{ AppResources.SquareInches, Area.SquareMiles.ToSquareInches },
						{ AppResources.Hectares, Area.SquareMiles.ToHectares },
						{ AppResources.Acres, Area.SquareMiles.ToAcres },
					}
				},
				{
					AppResources.SquareYards, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.SquareKilometres, Area.SquareYards.ToSquareKilometres },
						{ AppResources.SquareMetres, Area.SquareYards.ToSquareMetres },
						{ AppResources.SquareMiles, Area.SquareYards.ToSquareMiles },
						{ AppResources.SquareFeet, Area.SquareYards.ToSquareFeet },
						{ AppResources.SquareInches, Area.SquareYards.ToSquareInches },
						{ AppResources.Hectares, Area.SquareYards.ToHectares },
						{ AppResources.Acres, Area.SquareYards.ToAcres },
					}
				}
			};
		}

		public Dictionary<string, Dictionary<string, Func<double, double>>> Converters { get; }
	}
}
