// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

using PutridParrot.UnitsApi.Resources;
using PutridParrot.Units;

namespace PutridParrot.UnitsApi.Converters
{
	public partial class DataTransferRateConverters
	{
		public DataTransferRateConverters()
		{
			Converters = new Dictionary<string, Dictionary<string, Func<double, double>>>
			{
				{
					AppResources.BitsPerSecond, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.KiloBitsPerSecond, DataTransferRate.BitsPerSecond.ToKiloBitsPerSecond },
						{ AppResources.MegaBitsPerSecond, DataTransferRate.BitsPerSecond.ToMegaBitsPerSecond },
						{ AppResources.GigaBitsPerSecond, DataTransferRate.BitsPerSecond.ToGigaBitsPerSecond },
						{ AppResources.TeraBitsPerSecond, DataTransferRate.BitsPerSecond.ToTeraBitsPerSecond },
						{ AppResources.KiloBytesPerSecond, DataTransferRate.BitsPerSecond.ToKiloBytesPerSecond },
						{ AppResources.MegaBytesPerSecond, DataTransferRate.BitsPerSecond.ToMegaBytesPerSecond },
						{ AppResources.GigaBytesPerSecond, DataTransferRate.BitsPerSecond.ToGigaBytesPerSecond },
						{ AppResources.TeraBytesPerSecond, DataTransferRate.BitsPerSecond.ToTeraBytesPerSecond },
						{ AppResources.KibibitsPerSecond, DataTransferRate.BitsPerSecond.ToKibibitsPerSecond },
						{ AppResources.MebibitsPerSecond, DataTransferRate.BitsPerSecond.ToMebibitsPerSecond },
					}
				},
				{
					AppResources.GigaBitsPerSecond, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.BitsPerSecond, DataTransferRate.GigaBitsPerSecond.ToBitsPerSecond },
						{ AppResources.KiloBitsPerSecond, DataTransferRate.GigaBitsPerSecond.ToKiloBitsPerSecond },
						{ AppResources.MegaBitsPerSecond, DataTransferRate.GigaBitsPerSecond.ToMegaBitsPerSecond },
						{ AppResources.TeraBitsPerSecond, DataTransferRate.GigaBitsPerSecond.ToTeraBitsPerSecond },
						{ AppResources.KiloBytesPerSecond, DataTransferRate.GigaBitsPerSecond.ToKiloBytesPerSecond },
						{ AppResources.MegaBytesPerSecond, DataTransferRate.GigaBitsPerSecond.ToMegaBytesPerSecond },
						{ AppResources.GigaBytesPerSecond, DataTransferRate.GigaBitsPerSecond.ToGigaBytesPerSecond },
						{ AppResources.TeraBytesPerSecond, DataTransferRate.GigaBitsPerSecond.ToTeraBytesPerSecond },
						{ AppResources.KibibitsPerSecond, DataTransferRate.GigaBitsPerSecond.ToKibibitsPerSecond },
						{ AppResources.MebibitsPerSecond, DataTransferRate.GigaBitsPerSecond.ToMebibitsPerSecond },
					}
				},
				{
					AppResources.GigaBytesPerSecond, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.BitsPerSecond, DataTransferRate.GigaBytesPerSecond.ToBitsPerSecond },
						{ AppResources.KiloBitsPerSecond, DataTransferRate.GigaBytesPerSecond.ToKiloBitsPerSecond },
						{ AppResources.MegaBitsPerSecond, DataTransferRate.GigaBytesPerSecond.ToMegaBitsPerSecond },
						{ AppResources.GigaBitsPerSecond, DataTransferRate.GigaBytesPerSecond.ToGigaBitsPerSecond },
						{ AppResources.TeraBitsPerSecond, DataTransferRate.GigaBytesPerSecond.ToTeraBitsPerSecond },
						{ AppResources.KiloBytesPerSecond, DataTransferRate.GigaBytesPerSecond.ToKiloBytesPerSecond },
						{ AppResources.MegaBytesPerSecond, DataTransferRate.GigaBytesPerSecond.ToMegaBytesPerSecond },
						{ AppResources.TeraBytesPerSecond, DataTransferRate.GigaBytesPerSecond.ToTeraBytesPerSecond },
						{ AppResources.KibibitsPerSecond, DataTransferRate.GigaBytesPerSecond.ToKibibitsPerSecond },
						{ AppResources.MebibitsPerSecond, DataTransferRate.GigaBytesPerSecond.ToMebibitsPerSecond },
					}
				},
				{
					AppResources.KibibitsPerSecond, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.BitsPerSecond, DataTransferRate.KibibitsPerSecond.ToBitsPerSecond },
						{ AppResources.KiloBitsPerSecond, DataTransferRate.KibibitsPerSecond.ToKiloBitsPerSecond },
						{ AppResources.MegaBitsPerSecond, DataTransferRate.KibibitsPerSecond.ToMegaBitsPerSecond },
						{ AppResources.GigaBitsPerSecond, DataTransferRate.KibibitsPerSecond.ToGigaBitsPerSecond },
						{ AppResources.TeraBitsPerSecond, DataTransferRate.KibibitsPerSecond.ToTeraBitsPerSecond },
						{ AppResources.KiloBytesPerSecond, DataTransferRate.KibibitsPerSecond.ToKiloBytesPerSecond },
						{ AppResources.MegaBytesPerSecond, DataTransferRate.KibibitsPerSecond.ToMegaBytesPerSecond },
						{ AppResources.GigaBytesPerSecond, DataTransferRate.KibibitsPerSecond.ToGigaBytesPerSecond },
						{ AppResources.TeraBytesPerSecond, DataTransferRate.KibibitsPerSecond.ToTeraBytesPerSecond },
						{ AppResources.MebibitsPerSecond, DataTransferRate.KibibitsPerSecond.ToMebibitsPerSecond },
					}
				},
				{
					AppResources.KiloBitsPerSecond, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.BitsPerSecond, DataTransferRate.KiloBitsPerSecond.ToBitsPerSecond },
						{ AppResources.MegaBitsPerSecond, DataTransferRate.KiloBitsPerSecond.ToMegaBitsPerSecond },
						{ AppResources.GigaBitsPerSecond, DataTransferRate.KiloBitsPerSecond.ToGigaBitsPerSecond },
						{ AppResources.TeraBitsPerSecond, DataTransferRate.KiloBitsPerSecond.ToTeraBitsPerSecond },
						{ AppResources.KiloBytesPerSecond, DataTransferRate.KiloBitsPerSecond.ToKiloBytesPerSecond },
						{ AppResources.MegaBytesPerSecond, DataTransferRate.KiloBitsPerSecond.ToMegaBytesPerSecond },
						{ AppResources.GigaBytesPerSecond, DataTransferRate.KiloBitsPerSecond.ToGigaBytesPerSecond },
						{ AppResources.TeraBytesPerSecond, DataTransferRate.KiloBitsPerSecond.ToTeraBytesPerSecond },
						{ AppResources.KibibitsPerSecond, DataTransferRate.KiloBitsPerSecond.ToKibibitsPerSecond },
						{ AppResources.MebibitsPerSecond, DataTransferRate.KiloBitsPerSecond.ToMebibitsPerSecond },
					}
				},
				{
					AppResources.KiloBytesPerSecond, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.BitsPerSecond, DataTransferRate.KiloBytesPerSecond.ToBitsPerSecond },
						{ AppResources.KiloBitsPerSecond, DataTransferRate.KiloBytesPerSecond.ToKiloBitsPerSecond },
						{ AppResources.MegaBitsPerSecond, DataTransferRate.KiloBytesPerSecond.ToMegaBitsPerSecond },
						{ AppResources.GigaBitsPerSecond, DataTransferRate.KiloBytesPerSecond.ToGigaBitsPerSecond },
						{ AppResources.TeraBitsPerSecond, DataTransferRate.KiloBytesPerSecond.ToTeraBitsPerSecond },
						{ AppResources.MegaBytesPerSecond, DataTransferRate.KiloBytesPerSecond.ToMegaBytesPerSecond },
						{ AppResources.GigaBytesPerSecond, DataTransferRate.KiloBytesPerSecond.ToGigaBytesPerSecond },
						{ AppResources.TeraBytesPerSecond, DataTransferRate.KiloBytesPerSecond.ToTeraBytesPerSecond },
						{ AppResources.KibibitsPerSecond, DataTransferRate.KiloBytesPerSecond.ToKibibitsPerSecond },
						{ AppResources.MebibitsPerSecond, DataTransferRate.KiloBytesPerSecond.ToMebibitsPerSecond },
					}
				},
				{
					AppResources.MebibitsPerSecond, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.BitsPerSecond, DataTransferRate.MebibitsPerSecond.ToBitsPerSecond },
						{ AppResources.KiloBitsPerSecond, DataTransferRate.MebibitsPerSecond.ToKiloBitsPerSecond },
						{ AppResources.MegaBitsPerSecond, DataTransferRate.MebibitsPerSecond.ToMegaBitsPerSecond },
						{ AppResources.GigaBitsPerSecond, DataTransferRate.MebibitsPerSecond.ToGigaBitsPerSecond },
						{ AppResources.TeraBitsPerSecond, DataTransferRate.MebibitsPerSecond.ToTeraBitsPerSecond },
						{ AppResources.KiloBytesPerSecond, DataTransferRate.MebibitsPerSecond.ToKiloBytesPerSecond },
						{ AppResources.MegaBytesPerSecond, DataTransferRate.MebibitsPerSecond.ToMegaBytesPerSecond },
						{ AppResources.GigaBytesPerSecond, DataTransferRate.MebibitsPerSecond.ToGigaBytesPerSecond },
						{ AppResources.TeraBytesPerSecond, DataTransferRate.MebibitsPerSecond.ToTeraBytesPerSecond },
						{ AppResources.KibibitsPerSecond, DataTransferRate.MebibitsPerSecond.ToKibibitsPerSecond },
					}
				},
				{
					AppResources.MegaBitsPerSecond, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.BitsPerSecond, DataTransferRate.MegaBitsPerSecond.ToBitsPerSecond },
						{ AppResources.KiloBitsPerSecond, DataTransferRate.MegaBitsPerSecond.ToKiloBitsPerSecond },
						{ AppResources.GigaBitsPerSecond, DataTransferRate.MegaBitsPerSecond.ToGigaBitsPerSecond },
						{ AppResources.TeraBitsPerSecond, DataTransferRate.MegaBitsPerSecond.ToTeraBitsPerSecond },
						{ AppResources.KiloBytesPerSecond, DataTransferRate.MegaBitsPerSecond.ToKiloBytesPerSecond },
						{ AppResources.MegaBytesPerSecond, DataTransferRate.MegaBitsPerSecond.ToMegaBytesPerSecond },
						{ AppResources.GigaBytesPerSecond, DataTransferRate.MegaBitsPerSecond.ToGigaBytesPerSecond },
						{ AppResources.TeraBytesPerSecond, DataTransferRate.MegaBitsPerSecond.ToTeraBytesPerSecond },
						{ AppResources.KibibitsPerSecond, DataTransferRate.MegaBitsPerSecond.ToKibibitsPerSecond },
						{ AppResources.MebibitsPerSecond, DataTransferRate.MegaBitsPerSecond.ToMebibitsPerSecond },
					}
				},
				{
					AppResources.MegaBytesPerSecond, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.BitsPerSecond, DataTransferRate.MegaBytesPerSecond.ToBitsPerSecond },
						{ AppResources.KiloBitsPerSecond, DataTransferRate.MegaBytesPerSecond.ToKiloBitsPerSecond },
						{ AppResources.MegaBitsPerSecond, DataTransferRate.MegaBytesPerSecond.ToMegaBitsPerSecond },
						{ AppResources.GigaBitsPerSecond, DataTransferRate.MegaBytesPerSecond.ToGigaBitsPerSecond },
						{ AppResources.TeraBitsPerSecond, DataTransferRate.MegaBytesPerSecond.ToTeraBitsPerSecond },
						{ AppResources.KiloBytesPerSecond, DataTransferRate.MegaBytesPerSecond.ToKiloBytesPerSecond },
						{ AppResources.GigaBytesPerSecond, DataTransferRate.MegaBytesPerSecond.ToGigaBytesPerSecond },
						{ AppResources.TeraBytesPerSecond, DataTransferRate.MegaBytesPerSecond.ToTeraBytesPerSecond },
						{ AppResources.KibibitsPerSecond, DataTransferRate.MegaBytesPerSecond.ToKibibitsPerSecond },
						{ AppResources.MebibitsPerSecond, DataTransferRate.MegaBytesPerSecond.ToMebibitsPerSecond },
					}
				},
				{
					AppResources.TeraBitsPerSecond, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.BitsPerSecond, DataTransferRate.TeraBitsPerSecond.ToBitsPerSecond },
						{ AppResources.KiloBitsPerSecond, DataTransferRate.TeraBitsPerSecond.ToKiloBitsPerSecond },
						{ AppResources.MegaBitsPerSecond, DataTransferRate.TeraBitsPerSecond.ToMegaBitsPerSecond },
						{ AppResources.GigaBitsPerSecond, DataTransferRate.TeraBitsPerSecond.ToGigaBitsPerSecond },
						{ AppResources.KiloBytesPerSecond, DataTransferRate.TeraBitsPerSecond.ToKiloBytesPerSecond },
						{ AppResources.MegaBytesPerSecond, DataTransferRate.TeraBitsPerSecond.ToMegaBytesPerSecond },
						{ AppResources.GigaBytesPerSecond, DataTransferRate.TeraBitsPerSecond.ToGigaBytesPerSecond },
						{ AppResources.TeraBytesPerSecond, DataTransferRate.TeraBitsPerSecond.ToTeraBytesPerSecond },
						{ AppResources.KibibitsPerSecond, DataTransferRate.TeraBitsPerSecond.ToKibibitsPerSecond },
						{ AppResources.MebibitsPerSecond, DataTransferRate.TeraBitsPerSecond.ToMebibitsPerSecond },
					}
				},
				{
					AppResources.TeraBytesPerSecond, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.BitsPerSecond, DataTransferRate.TeraBytesPerSecond.ToBitsPerSecond },
						{ AppResources.KiloBitsPerSecond, DataTransferRate.TeraBytesPerSecond.ToKiloBitsPerSecond },
						{ AppResources.MegaBitsPerSecond, DataTransferRate.TeraBytesPerSecond.ToMegaBitsPerSecond },
						{ AppResources.GigaBitsPerSecond, DataTransferRate.TeraBytesPerSecond.ToGigaBitsPerSecond },
						{ AppResources.TeraBitsPerSecond, DataTransferRate.TeraBytesPerSecond.ToTeraBitsPerSecond },
						{ AppResources.KiloBytesPerSecond, DataTransferRate.TeraBytesPerSecond.ToKiloBytesPerSecond },
						{ AppResources.MegaBytesPerSecond, DataTransferRate.TeraBytesPerSecond.ToMegaBytesPerSecond },
						{ AppResources.GigaBytesPerSecond, DataTransferRate.TeraBytesPerSecond.ToGigaBytesPerSecond },
						{ AppResources.KibibitsPerSecond, DataTransferRate.TeraBytesPerSecond.ToKibibitsPerSecond },
						{ AppResources.MebibitsPerSecond, DataTransferRate.TeraBytesPerSecond.ToMebibitsPerSecond },
					}
				}
			};
		}

		public Dictionary<string, Dictionary<string, Func<double, double>>> Converters { get; }
	}
}
