// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

using PutridParrot.UnitsApi.Resources;
using PutridParrot.Units;

namespace PutridParrot.UnitsApi.Converters
{
	public partial class ForceConverters
	{
		public ForceConverters()
		{
			Converters = new Dictionary<string, Dictionary<string, Func<double, double>>>
			{
				{
					AppResources.Dynes, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Newtons, Force.Dynes.ToNewtons },
						{ AppResources.Poundals, Force.Dynes.ToPoundals },
						{ AppResources.Kilogramforce, Force.Dynes.ToKilogramforce },
					}
				},
				{
					AppResources.Kilogramforce, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Newtons, Force.Kilogramforce.ToNewtons },
						{ AppResources.Dynes, Force.Kilogramforce.ToDynes },
						{ AppResources.Poundals, Force.Kilogramforce.ToPoundals },
					}
				},
				{
					AppResources.Newtons, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Dynes, Force.Newtons.ToDynes },
						{ AppResources.Poundals, Force.Newtons.ToPoundals },
						{ AppResources.Kilogramforce, Force.Newtons.ToKilogramforce },
					}
				},
				{
					AppResources.Poundals, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Newtons, Force.Poundals.ToNewtons },
						{ AppResources.Dynes, Force.Poundals.ToDynes },
						{ AppResources.Kilogramforce, Force.Poundals.ToKilogramforce },
					}
				}
			};
		}

		public Dictionary<string, Dictionary<string, Func<double, double>>> Converters { get; }
	}
}
