// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

using PutridParrot.UnitsApi.Resources;
using PutridParrot.Units;

namespace PutridParrot.UnitsApi.Converters
{
	public partial class FrequencyConverters
	{
		public FrequencyConverters()
		{
			Converters = new Dictionary<string, Dictionary<string, Func<double, double>>>
			{
				{
					AppResources.Gigahertz, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Hertz, Frequency.Gigahertz.ToHertz },
						{ AppResources.Kilohertz, Frequency.Gigahertz.ToKilohertz },
						{ AppResources.Megahertz, Frequency.Gigahertz.ToMegahertz },
					}
				},
				{
					AppResources.Hertz, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Kilohertz, Frequency.Hertz.ToKilohertz },
						{ AppResources.Megahertz, Frequency.Hertz.ToMegahertz },
						{ AppResources.Gigahertz, Frequency.Hertz.ToGigahertz },
					}
				},
				{
					AppResources.Kilohertz, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Hertz, Frequency.Kilohertz.ToHertz },
						{ AppResources.Megahertz, Frequency.Kilohertz.ToMegahertz },
						{ AppResources.Gigahertz, Frequency.Kilohertz.ToGigahertz },
					}
				},
				{
					AppResources.Megahertz, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Hertz, Frequency.Megahertz.ToHertz },
						{ AppResources.Kilohertz, Frequency.Megahertz.ToKilohertz },
						{ AppResources.Gigahertz, Frequency.Megahertz.ToGigahertz },
					}
				}
			};
		}

		public Dictionary<string, Dictionary<string, Func<double, double>>> Converters { get; }
	}
}
