// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

using System;
using System.Collections.Generic;
using PutridParrot.UnitsApi.Resources;
using PutridParrot.Units;

namespace PutridParrot.UnitsApi.Converters
{
	public partial class LengthConverters
	{
		public LengthConverters()
		{
			Converters = new Dictionary<string, Dictionary<string, Func<double, double>>>
			{
				{
					AppResources.Centimetres, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Millimetres, Length.Centimetres.ToMillimetres },
						{ AppResources.Metres, Length.Centimetres.ToMetres },
						{ AppResources.Kilometres, Length.Centimetres.ToKilometres },
						{ AppResources.Inches, Length.Centimetres.ToInches },
						{ AppResources.Feet, Length.Centimetres.ToFeet },
						{ AppResources.Yards, Length.Centimetres.ToYards },
						{ AppResources.Miles, Length.Centimetres.ToMiles },
						{ AppResources.NauticalMiles, Length.Centimetres.ToNauticalMiles },
					}
				},
				{
					AppResources.Feet, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Millimetres, Length.Feet.ToMillimetres },
						{ AppResources.Centimetres, Length.Feet.ToCentimetres },
						{ AppResources.Metres, Length.Feet.ToMetres },
						{ AppResources.Kilometres, Length.Feet.ToKilometres },
						{ AppResources.Inches, Length.Feet.ToInches },
						{ AppResources.Yards, Length.Feet.ToYards },
						{ AppResources.Miles, Length.Feet.ToMiles },
						{ AppResources.NauticalMiles, Length.Feet.ToNauticalMiles },
					}
				},
				{
					AppResources.Inches, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Millimetres, Length.Inches.ToMillimetres },
						{ AppResources.Centimetres, Length.Inches.ToCentimetres },
						{ AppResources.Metres, Length.Inches.ToMetres },
						{ AppResources.Kilometres, Length.Inches.ToKilometres },
						{ AppResources.Feet, Length.Inches.ToFeet },
						{ AppResources.Yards, Length.Inches.ToYards },
						{ AppResources.Miles, Length.Inches.ToMiles },
						{ AppResources.NauticalMiles, Length.Inches.ToNauticalMiles },
					}
				},
				{
					AppResources.Kilometres, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Millimetres, Length.Kilometres.ToMillimetres },
						{ AppResources.Centimetres, Length.Kilometres.ToCentimetres },
						{ AppResources.Metres, Length.Kilometres.ToMetres },
						{ AppResources.Inches, Length.Kilometres.ToInches },
						{ AppResources.Feet, Length.Kilometres.ToFeet },
						{ AppResources.Yards, Length.Kilometres.ToYards },
						{ AppResources.Miles, Length.Kilometres.ToMiles },
						{ AppResources.NauticalMiles, Length.Kilometres.ToNauticalMiles },
					}
				},
				{
					AppResources.Metres, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Millimetres, Length.Metres.ToMillimetres },
						{ AppResources.Centimetres, Length.Metres.ToCentimetres },
						{ AppResources.Kilometres, Length.Metres.ToKilometres },
						{ AppResources.Inches, Length.Metres.ToInches },
						{ AppResources.Feet, Length.Metres.ToFeet },
						{ AppResources.Yards, Length.Metres.ToYards },
						{ AppResources.Miles, Length.Metres.ToMiles },
						{ AppResources.NauticalMiles, Length.Metres.ToNauticalMiles },
					}
				},
				{
					AppResources.Miles, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Millimetres, Length.Miles.ToMillimetres },
						{ AppResources.Centimetres, Length.Miles.ToCentimetres },
						{ AppResources.Metres, Length.Miles.ToMetres },
						{ AppResources.Kilometres, Length.Miles.ToKilometres },
						{ AppResources.Inches, Length.Miles.ToInches },
						{ AppResources.Feet, Length.Miles.ToFeet },
						{ AppResources.Yards, Length.Miles.ToYards },
						{ AppResources.NauticalMiles, Length.Miles.ToNauticalMiles },
					}
				},
				{
					AppResources.Millimetres, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Centimetres, Length.Millimetres.ToCentimetres },
						{ AppResources.Metres, Length.Millimetres.ToMetres },
						{ AppResources.Kilometres, Length.Millimetres.ToKilometres },
						{ AppResources.Inches, Length.Millimetres.ToInches },
						{ AppResources.Feet, Length.Millimetres.ToFeet },
						{ AppResources.Yards, Length.Millimetres.ToYards },
						{ AppResources.Miles, Length.Millimetres.ToMiles },
						{ AppResources.NauticalMiles, Length.Millimetres.ToNauticalMiles },
					}
				},
				{
					AppResources.NauticalMiles, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Millimetres, Length.NauticalMiles.ToMillimetres },
						{ AppResources.Centimetres, Length.NauticalMiles.ToCentimetres },
						{ AppResources.Metres, Length.NauticalMiles.ToMetres },
						{ AppResources.Kilometres, Length.NauticalMiles.ToKilometres },
						{ AppResources.Inches, Length.NauticalMiles.ToInches },
						{ AppResources.Feet, Length.NauticalMiles.ToFeet },
						{ AppResources.Yards, Length.NauticalMiles.ToYards },
						{ AppResources.Miles, Length.NauticalMiles.ToMiles },
					}
				},
				{
					AppResources.Yards, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Millimetres, Length.Yards.ToMillimetres },
						{ AppResources.Centimetres, Length.Yards.ToCentimetres },
						{ AppResources.Metres, Length.Yards.ToMetres },
						{ AppResources.Kilometres, Length.Yards.ToKilometres },
						{ AppResources.Inches, Length.Yards.ToInches },
						{ AppResources.Feet, Length.Yards.ToFeet },
						{ AppResources.Miles, Length.Yards.ToMiles },
						{ AppResources.NauticalMiles, Length.Yards.ToNauticalMiles },
					}
				}
			};
		}

		public Dictionary<string, Dictionary<string, Func<double, double>>> Converters { get; }
	}
}
