// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

using PutridParrot.UnitsApi.Resources;
using PutridParrot.Units;

namespace PutridParrot.UnitsApi.Converters
{
	public partial class LuminousEnergyConverters
	{
		public LuminousEnergyConverters()
		{
			Converters = new Dictionary<string, Dictionary<string, Func<double, double>>>
			{
				{
					AppResources.LumenHour, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Talbot, LuminousEnergy.LumenHour.ToTalbot },
						{ AppResources.LumenMinute, LuminousEnergy.LumenHour.ToLumenMinute },
						{ AppResources.LumenSecond, LuminousEnergy.LumenHour.ToLumenSecond },
					}
				},
				{
					AppResources.LumenMinute, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Talbot, LuminousEnergy.LumenMinute.ToTalbot },
						{ AppResources.LumenHour, LuminousEnergy.LumenMinute.ToLumenHour },
						{ AppResources.LumenSecond, LuminousEnergy.LumenMinute.ToLumenSecond },
					}
				},
				{
					AppResources.LumenSecond, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Talbot, LuminousEnergy.LumenSecond.ToTalbot },
						{ AppResources.LumenHour, LuminousEnergy.LumenSecond.ToLumenHour },
						{ AppResources.LumenMinute, LuminousEnergy.LumenSecond.ToLumenMinute },
					}
				},
				{
					AppResources.Talbot, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.LumenSecond, LuminousEnergy.Talbot.ToLumenSecond },
						{ AppResources.LumenHour, LuminousEnergy.Talbot.ToLumenHour },
						{ AppResources.LumenMinute, LuminousEnergy.Talbot.ToLumenMinute },
					}
				}
			};
		}

		public Dictionary<string, Dictionary<string, Func<double, double>>> Converters { get; }
	}
}
