// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

using PutridParrot.UnitsApi.Resources;
using PutridParrot.Units;

namespace PutridParrot.UnitsApi.Converters
{
	public partial class MagnetomotiveForceConverters
	{
		public MagnetomotiveForceConverters()
		{
			Converters = new Dictionary<string, Dictionary<string, Func<double, double>>>
			{
				{
					AppResources.Ampereturns, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Gilberts, MagnetomotiveForce.Ampereturns.ToGilberts },
					}
				},
				{
					AppResources.Gilberts, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Ampereturns, MagnetomotiveForce.Gilberts.ToAmpereturns },
					}
				}
			};
		}

		public Dictionary<string, Dictionary<string, Func<double, double>>> Converters { get; }
	}
}
