// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

using PutridParrot.UnitsApi.Resources;
using PutridParrot.Units;

namespace PutridParrot.UnitsApi.Converters
{
	public partial class MassConverters
	{
		public MassConverters()
		{
			Converters = new Dictionary<string, Dictionary<string, Func<double, double>>>
			{
				{
					AppResources.Carats, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Milligrams, Mass.Carats.ToMilligrams },
						{ AppResources.Grams, Mass.Carats.ToGrams },
						{ AppResources.Kilograms, Mass.Carats.ToKilograms },
						{ AppResources.Tonnes, Mass.Carats.ToTonnes },
						{ AppResources.Ounces, Mass.Carats.ToOunces },
						{ AppResources.Pounds, Mass.Carats.ToPounds },
						{ AppResources.Stones, Mass.Carats.ToStones },
					}
				},
				{
					AppResources.Grams, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Milligrams, Mass.Grams.ToMilligrams },
						{ AppResources.Kilograms, Mass.Grams.ToKilograms },
						{ AppResources.Tonnes, Mass.Grams.ToTonnes },
						{ AppResources.Ounces, Mass.Grams.ToOunces },
						{ AppResources.Pounds, Mass.Grams.ToPounds },
						{ AppResources.Stones, Mass.Grams.ToStones },
						{ AppResources.Carats, Mass.Grams.ToCarats },
					}
				},
				{
					AppResources.Kilograms, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Milligrams, Mass.Kilograms.ToMilligrams },
						{ AppResources.Grams, Mass.Kilograms.ToGrams },
						{ AppResources.Tonnes, Mass.Kilograms.ToTonnes },
						{ AppResources.Ounces, Mass.Kilograms.ToOunces },
						{ AppResources.Pounds, Mass.Kilograms.ToPounds },
						{ AppResources.Stones, Mass.Kilograms.ToStones },
						{ AppResources.Carats, Mass.Kilograms.ToCarats },
					}
				},
				{
					AppResources.Milligrams, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Grams, Mass.Milligrams.ToGrams },
						{ AppResources.Kilograms, Mass.Milligrams.ToKilograms },
						{ AppResources.Tonnes, Mass.Milligrams.ToTonnes },
						{ AppResources.Ounces, Mass.Milligrams.ToOunces },
						{ AppResources.Pounds, Mass.Milligrams.ToPounds },
						{ AppResources.Stones, Mass.Milligrams.ToStones },
						{ AppResources.Carats, Mass.Milligrams.ToCarats },
					}
				},
				{
					AppResources.Ounces, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Milligrams, Mass.Ounces.ToMilligrams },
						{ AppResources.Grams, Mass.Ounces.ToGrams },
						{ AppResources.Kilograms, Mass.Ounces.ToKilograms },
						{ AppResources.Tonnes, Mass.Ounces.ToTonnes },
						{ AppResources.Pounds, Mass.Ounces.ToPounds },
						{ AppResources.Stones, Mass.Ounces.ToStones },
						{ AppResources.Carats, Mass.Ounces.ToCarats },
					}
				},
				{
					AppResources.Pounds, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Milligrams, Mass.Pounds.ToMilligrams },
						{ AppResources.Grams, Mass.Pounds.ToGrams },
						{ AppResources.Kilograms, Mass.Pounds.ToKilograms },
						{ AppResources.Tonnes, Mass.Pounds.ToTonnes },
						{ AppResources.Ounces, Mass.Pounds.ToOunces },
						{ AppResources.Stones, Mass.Pounds.ToStones },
						{ AppResources.Carats, Mass.Pounds.ToCarats },
					}
				},
				{
					AppResources.Stones, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Milligrams, Mass.Stones.ToMilligrams },
						{ AppResources.Grams, Mass.Stones.ToGrams },
						{ AppResources.Kilograms, Mass.Stones.ToKilograms },
						{ AppResources.Tonnes, Mass.Stones.ToTonnes },
						{ AppResources.Ounces, Mass.Stones.ToOunces },
						{ AppResources.Pounds, Mass.Stones.ToPounds },
						{ AppResources.Carats, Mass.Stones.ToCarats },
					}
				},
				{
					AppResources.Tonnes, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Milligrams, Mass.Tonnes.ToMilligrams },
						{ AppResources.Grams, Mass.Tonnes.ToGrams },
						{ AppResources.Kilograms, Mass.Tonnes.ToKilograms },
						{ AppResources.Ounces, Mass.Tonnes.ToOunces },
						{ AppResources.Pounds, Mass.Tonnes.ToPounds },
						{ AppResources.Stones, Mass.Tonnes.ToStones },
						{ AppResources.Carats, Mass.Tonnes.ToCarats },
					}
				}
			};
		}

		public Dictionary<string, Dictionary<string, Func<double, double>>> Converters { get; }
	}
}
