// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

using PutridParrot.UnitsApi.Resources;
using PutridParrot.Units;

namespace PutridParrot.UnitsApi.Converters
{
	public partial class PowerConverters
	{
		public PowerConverters()
		{
			Converters = new Dictionary<string, Dictionary<string, Func<double, double>>>
			{
				{
					AppResources.MechanicalHorsePower, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.MetricHorsePower, Power.MechanicalHorsePower.ToMetricHorsePower },
					}
				},
				{
					AppResources.MetricHorsePower, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.MechanicalHorsePower, Power.MetricHorsePower.ToMechanicalHorsePower },
					}
				}
			};
		}

		public Dictionary<string, Dictionary<string, Func<double, double>>> Converters { get; }
	}
}
