// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

using PutridParrot.UnitsApi.Resources;
using PutridParrot.Units;

namespace PutridParrot.UnitsApi.Converters
{
	public partial class PressureConverters
	{
		public PressureConverters()
		{
			Converters = new Dictionary<string, Dictionary<string, Func<double, double>>>
			{
				{
					AppResources.Atmospheres, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Bars, Pressure.Atmospheres.ToBars },
						{ AppResources.Pascals, Pressure.Atmospheres.ToPascals },
						{ AppResources.Torrs, Pressure.Atmospheres.ToTorrs },
						{ AppResources.Psi, Pressure.Atmospheres.ToPsi },
					}
				},
				{
					AppResources.Bars, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Atmospheres, Pressure.Bars.ToAtmospheres },
						{ AppResources.Pascals, Pressure.Bars.ToPascals },
						{ AppResources.Torrs, Pressure.Bars.ToTorrs },
						{ AppResources.Psi, Pressure.Bars.ToPsi },
					}
				},
				{
					AppResources.Pascals, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Atmospheres, Pressure.Pascals.ToAtmospheres },
						{ AppResources.Bars, Pressure.Pascals.ToBars },
						{ AppResources.Torrs, Pressure.Pascals.ToTorrs },
						{ AppResources.Psi, Pressure.Pascals.ToPsi },
					}
				},
				{
					AppResources.Psi, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Bars, Pressure.Psi.ToBars },
						{ AppResources.Pascals, Pressure.Psi.ToPascals },
						{ AppResources.Atmospheres, Pressure.Psi.ToAtmospheres },
						{ AppResources.Torrs, Pressure.Psi.ToTorrs },
					}
				},
				{
					AppResources.Torrs, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Bars, Pressure.Torrs.ToBars },
						{ AppResources.Pascals, Pressure.Torrs.ToPascals },
						{ AppResources.Atmospheres, Pressure.Torrs.ToAtmospheres },
						{ AppResources.Psi, Pressure.Torrs.ToPsi },
					}
				}
			};
		}

		public Dictionary<string, Dictionary<string, Func<double, double>>> Converters { get; }
	}
}
