// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

using PutridParrot.UnitsApi.Resources;
using PutridParrot.Units;

namespace PutridParrot.UnitsApi.Converters
{
	public partial class SpeedConverters
	{
		public SpeedConverters()
		{
			Converters = new Dictionary<string, Dictionary<string, Func<double, double>>>
			{
				{
					AppResources.FeetPerSecond, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.MilesPerHour, Speed.FeetPerSecond.ToMilesPerHour },
						{ AppResources.KilometresPerHour, Speed.FeetPerSecond.ToKilometresPerHour },
						{ AppResources.MetresPerSecond, Speed.FeetPerSecond.ToMetresPerSecond },
						{ AppResources.Knots, Speed.FeetPerSecond.ToKnots },
					}
				},
				{
					AppResources.KilometresPerHour, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.MilesPerHour, Speed.KilometresPerHour.ToMilesPerHour },
						{ AppResources.FeetPerSecond, Speed.KilometresPerHour.ToFeetPerSecond },
						{ AppResources.MetresPerSecond, Speed.KilometresPerHour.ToMetresPerSecond },
						{ AppResources.Knots, Speed.KilometresPerHour.ToKnots },
					}
				},
				{
					AppResources.Knots, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.MilesPerHour, Speed.Knots.ToMilesPerHour },
						{ AppResources.KilometresPerHour, Speed.Knots.ToKilometresPerHour },
						{ AppResources.FeetPerSecond, Speed.Knots.ToFeetPerSecond },
						{ AppResources.MetresPerSecond, Speed.Knots.ToMetresPerSecond },
					}
				},
				{
					AppResources.MetresPerSecond, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.MilesPerHour, Speed.MetresPerSecond.ToMilesPerHour },
						{ AppResources.KilometresPerHour, Speed.MetresPerSecond.ToKilometresPerHour },
						{ AppResources.FeetPerSecond, Speed.MetresPerSecond.ToFeetPerSecond },
						{ AppResources.Knots, Speed.MetresPerSecond.ToKnots },
					}
				},
				{
					AppResources.MilesPerHour, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.KilometresPerHour, Speed.MilesPerHour.ToKilometresPerHour },
						{ AppResources.FeetPerSecond, Speed.MilesPerHour.ToFeetPerSecond },
						{ AppResources.MetresPerSecond, Speed.MilesPerHour.ToMetresPerSecond },
						{ AppResources.Knots, Speed.MilesPerHour.ToKnots },
					}
				}
			};
		}

		public Dictionary<string, Dictionary<string, Func<double, double>>> Converters { get; }
	}
}
