// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

using PutridParrot.UnitsApi.Resources;
using PutridParrot.Units;

namespace PutridParrot.UnitsApi.Converters
{
	public partial class TemperatureConverters
	{
		public TemperatureConverters()
		{
			Converters = new Dictionary<string, Dictionary<string, Func<double, double>>>
			{
				{
					AppResources.Celsius, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Fahrenheit, Temperature.Celsius.ToFahrenheit },
						{ AppResources.Kelvin, Temperature.Celsius.ToKelvin },
						{ AppResources.Rankine, Temperature.Celsius.ToRankine },
					}
				},
				{
					AppResources.Fahrenheit, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Celsius, Temperature.Fahrenheit.ToCelsius },
						{ AppResources.Kelvin, Temperature.Fahrenheit.ToKelvin },
						{ AppResources.Rankine, Temperature.Fahrenheit.ToRankine },
					}
				},
				{
					AppResources.Kelvin, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Celsius, Temperature.Kelvin.ToCelsius },
						{ AppResources.Fahrenheit, Temperature.Kelvin.ToFahrenheit },
						{ AppResources.Rankine, Temperature.Kelvin.ToRankine },
					}
				},
				{
					AppResources.Rankine, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Celsius, Temperature.Rankine.ToCelsius },
						{ AppResources.Fahrenheit, Temperature.Rankine.ToFahrenheit },
						{ AppResources.Kelvin, Temperature.Rankine.ToKelvin },
					}
				}
			};
		}

		public Dictionary<string, Dictionary<string, Func<double, double>>> Converters { get; }
	}
}
