// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

using PutridParrot.UnitsApi.Resources;
using PutridParrot.Units;

namespace PutridParrot.UnitsApi.Converters
{
	public partial class VolumeConverters
	{
		public VolumeConverters()
		{
			Converters = new Dictionary<string, Dictionary<string, Func<double, double>>>
			{
				{
					AppResources.CubicFeet, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Millilitres, Volume.CubicFeet.ToMillilitres },
						{ AppResources.Litres, Volume.CubicFeet.ToLitres },
						{ AppResources.Kilolitres, Volume.CubicFeet.ToKilolitres },
						{ AppResources.Teaspoons, Volume.CubicFeet.ToTeaspoons },
						{ AppResources.Tablespoons, Volume.CubicFeet.ToTablespoons },
						{ AppResources.Quarts, Volume.CubicFeet.ToQuarts },
						{ AppResources.Pints, Volume.CubicFeet.ToPints },
						{ AppResources.Gallons, Volume.CubicFeet.ToGallons },
						{ AppResources.FluidOunces, Volume.CubicFeet.ToFluidOunces },
						{ AppResources.USTeaspoons, Volume.CubicFeet.ToUSTeaspoons },
						{ AppResources.USTablespoons, Volume.CubicFeet.ToUSTablespoons },
						{ AppResources.USQuarts, Volume.CubicFeet.ToUSQuarts },
						{ AppResources.USPints, Volume.CubicFeet.ToUSPints },
						{ AppResources.USGallons, Volume.CubicFeet.ToUSGallons },
						{ AppResources.USFluidOunces, Volume.CubicFeet.ToUSFluidOunces },
						{ AppResources.USCups, Volume.CubicFeet.ToUSCups },
						{ AppResources.CubicMetres, Volume.CubicFeet.ToCubicMetres },
						{ AppResources.CubicInches, Volume.CubicFeet.ToCubicInches },
						{ AppResources.OilBarrels, Volume.CubicFeet.ToOilBarrels },
					}
				},
				{
					AppResources.CubicInches, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Millilitres, Volume.CubicInches.ToMillilitres },
						{ AppResources.Litres, Volume.CubicInches.ToLitres },
						{ AppResources.Kilolitres, Volume.CubicInches.ToKilolitres },
						{ AppResources.Teaspoons, Volume.CubicInches.ToTeaspoons },
						{ AppResources.Tablespoons, Volume.CubicInches.ToTablespoons },
						{ AppResources.Quarts, Volume.CubicInches.ToQuarts },
						{ AppResources.Pints, Volume.CubicInches.ToPints },
						{ AppResources.Gallons, Volume.CubicInches.ToGallons },
						{ AppResources.FluidOunces, Volume.CubicInches.ToFluidOunces },
						{ AppResources.USTeaspoons, Volume.CubicInches.ToUSTeaspoons },
						{ AppResources.USTablespoons, Volume.CubicInches.ToUSTablespoons },
						{ AppResources.USQuarts, Volume.CubicInches.ToUSQuarts },
						{ AppResources.USPints, Volume.CubicInches.ToUSPints },
						{ AppResources.USGallons, Volume.CubicInches.ToUSGallons },
						{ AppResources.USFluidOunces, Volume.CubicInches.ToUSFluidOunces },
						{ AppResources.USCups, Volume.CubicInches.ToUSCups },
						{ AppResources.CubicMetres, Volume.CubicInches.ToCubicMetres },
						{ AppResources.CubicFeet, Volume.CubicInches.ToCubicFeet },
						{ AppResources.OilBarrels, Volume.CubicInches.ToOilBarrels },
					}
				},
				{
					AppResources.CubicMetres, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Millilitres, Volume.CubicMetres.ToMillilitres },
						{ AppResources.Litres, Volume.CubicMetres.ToLitres },
						{ AppResources.Kilolitres, Volume.CubicMetres.ToKilolitres },
						{ AppResources.Teaspoons, Volume.CubicMetres.ToTeaspoons },
						{ AppResources.Tablespoons, Volume.CubicMetres.ToTablespoons },
						{ AppResources.Quarts, Volume.CubicMetres.ToQuarts },
						{ AppResources.Pints, Volume.CubicMetres.ToPints },
						{ AppResources.Gallons, Volume.CubicMetres.ToGallons },
						{ AppResources.FluidOunces, Volume.CubicMetres.ToFluidOunces },
						{ AppResources.USTeaspoons, Volume.CubicMetres.ToUSTeaspoons },
						{ AppResources.USTablespoons, Volume.CubicMetres.ToUSTablespoons },
						{ AppResources.USQuarts, Volume.CubicMetres.ToUSQuarts },
						{ AppResources.USPints, Volume.CubicMetres.ToUSPints },
						{ AppResources.USGallons, Volume.CubicMetres.ToUSGallons },
						{ AppResources.USFluidOunces, Volume.CubicMetres.ToUSFluidOunces },
						{ AppResources.USCups, Volume.CubicMetres.ToUSCups },
						{ AppResources.CubicFeet, Volume.CubicMetres.ToCubicFeet },
						{ AppResources.CubicInches, Volume.CubicMetres.ToCubicInches },
						{ AppResources.OilBarrels, Volume.CubicMetres.ToOilBarrels },
					}
				},
				{
					AppResources.FluidOunces, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Millilitres, Volume.FluidOunces.ToMillilitres },
						{ AppResources.Litres, Volume.FluidOunces.ToLitres },
						{ AppResources.Kilolitres, Volume.FluidOunces.ToKilolitres },
						{ AppResources.Teaspoons, Volume.FluidOunces.ToTeaspoons },
						{ AppResources.Tablespoons, Volume.FluidOunces.ToTablespoons },
						{ AppResources.Quarts, Volume.FluidOunces.ToQuarts },
						{ AppResources.Pints, Volume.FluidOunces.ToPints },
						{ AppResources.Gallons, Volume.FluidOunces.ToGallons },
						{ AppResources.USTeaspoons, Volume.FluidOunces.ToUSTeaspoons },
						{ AppResources.USTablespoons, Volume.FluidOunces.ToUSTablespoons },
						{ AppResources.USQuarts, Volume.FluidOunces.ToUSQuarts },
						{ AppResources.USPints, Volume.FluidOunces.ToUSPints },
						{ AppResources.USGallons, Volume.FluidOunces.ToUSGallons },
						{ AppResources.USFluidOunces, Volume.FluidOunces.ToUSFluidOunces },
						{ AppResources.USCups, Volume.FluidOunces.ToUSCups },
						{ AppResources.CubicMetres, Volume.FluidOunces.ToCubicMetres },
						{ AppResources.CubicFeet, Volume.FluidOunces.ToCubicFeet },
						{ AppResources.CubicInches, Volume.FluidOunces.ToCubicInches },
						{ AppResources.OilBarrels, Volume.FluidOunces.ToOilBarrels },
					}
				},
				{
					AppResources.Gallons, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Millilitres, Volume.Gallons.ToMillilitres },
						{ AppResources.Litres, Volume.Gallons.ToLitres },
						{ AppResources.Kilolitres, Volume.Gallons.ToKilolitres },
						{ AppResources.Teaspoons, Volume.Gallons.ToTeaspoons },
						{ AppResources.Tablespoons, Volume.Gallons.ToTablespoons },
						{ AppResources.Quarts, Volume.Gallons.ToQuarts },
						{ AppResources.Pints, Volume.Gallons.ToPints },
						{ AppResources.FluidOunces, Volume.Gallons.ToFluidOunces },
						{ AppResources.USTeaspoons, Volume.Gallons.ToUSTeaspoons },
						{ AppResources.USTablespoons, Volume.Gallons.ToUSTablespoons },
						{ AppResources.USQuarts, Volume.Gallons.ToUSQuarts },
						{ AppResources.USPints, Volume.Gallons.ToUSPints },
						{ AppResources.USGallons, Volume.Gallons.ToUSGallons },
						{ AppResources.USFluidOunces, Volume.Gallons.ToUSFluidOunces },
						{ AppResources.USCups, Volume.Gallons.ToUSCups },
						{ AppResources.CubicMetres, Volume.Gallons.ToCubicMetres },
						{ AppResources.CubicFeet, Volume.Gallons.ToCubicFeet },
						{ AppResources.CubicInches, Volume.Gallons.ToCubicInches },
						{ AppResources.OilBarrels, Volume.Gallons.ToOilBarrels },
					}
				},
				{
					AppResources.Kilolitres, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Millilitres, Volume.Kilolitres.ToMillilitres },
						{ AppResources.Litres, Volume.Kilolitres.ToLitres },
						{ AppResources.Teaspoons, Volume.Kilolitres.ToTeaspoons },
						{ AppResources.Tablespoons, Volume.Kilolitres.ToTablespoons },
						{ AppResources.Quarts, Volume.Kilolitres.ToQuarts },
						{ AppResources.Pints, Volume.Kilolitres.ToPints },
						{ AppResources.Gallons, Volume.Kilolitres.ToGallons },
						{ AppResources.FluidOunces, Volume.Kilolitres.ToFluidOunces },
						{ AppResources.USTeaspoons, Volume.Kilolitres.ToUSTeaspoons },
						{ AppResources.USTablespoons, Volume.Kilolitres.ToUSTablespoons },
						{ AppResources.USQuarts, Volume.Kilolitres.ToUSQuarts },
						{ AppResources.USPints, Volume.Kilolitres.ToUSPints },
						{ AppResources.USGallons, Volume.Kilolitres.ToUSGallons },
						{ AppResources.USFluidOunces, Volume.Kilolitres.ToUSFluidOunces },
						{ AppResources.USCups, Volume.Kilolitres.ToUSCups },
						{ AppResources.CubicMetres, Volume.Kilolitres.ToCubicMetres },
						{ AppResources.CubicFeet, Volume.Kilolitres.ToCubicFeet },
						{ AppResources.CubicInches, Volume.Kilolitres.ToCubicInches },
						{ AppResources.OilBarrels, Volume.Kilolitres.ToOilBarrels },
					}
				},
				{
					AppResources.Litres, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Millilitres, Volume.Litres.ToMillilitres },
						{ AppResources.Kilolitres, Volume.Litres.ToKilolitres },
						{ AppResources.Teaspoons, Volume.Litres.ToTeaspoons },
						{ AppResources.Tablespoons, Volume.Litres.ToTablespoons },
						{ AppResources.Quarts, Volume.Litres.ToQuarts },
						{ AppResources.Pints, Volume.Litres.ToPints },
						{ AppResources.Gallons, Volume.Litres.ToGallons },
						{ AppResources.FluidOunces, Volume.Litres.ToFluidOunces },
						{ AppResources.USTeaspoons, Volume.Litres.ToUSTeaspoons },
						{ AppResources.USTablespoons, Volume.Litres.ToUSTablespoons },
						{ AppResources.USQuarts, Volume.Litres.ToUSQuarts },
						{ AppResources.USPints, Volume.Litres.ToUSPints },
						{ AppResources.USGallons, Volume.Litres.ToUSGallons },
						{ AppResources.USFluidOunces, Volume.Litres.ToUSFluidOunces },
						{ AppResources.USCups, Volume.Litres.ToUSCups },
						{ AppResources.CubicMetres, Volume.Litres.ToCubicMetres },
						{ AppResources.CubicFeet, Volume.Litres.ToCubicFeet },
						{ AppResources.CubicInches, Volume.Litres.ToCubicInches },
						{ AppResources.OilBarrels, Volume.Litres.ToOilBarrels },
					}
				},
				{
					AppResources.Millilitres, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Litres, Volume.Millilitres.ToLitres },
						{ AppResources.Kilolitres, Volume.Millilitres.ToKilolitres },
						{ AppResources.Teaspoons, Volume.Millilitres.ToTeaspoons },
						{ AppResources.Tablespoons, Volume.Millilitres.ToTablespoons },
						{ AppResources.Quarts, Volume.Millilitres.ToQuarts },
						{ AppResources.Pints, Volume.Millilitres.ToPints },
						{ AppResources.Gallons, Volume.Millilitres.ToGallons },
						{ AppResources.FluidOunces, Volume.Millilitres.ToFluidOunces },
						{ AppResources.USTeaspoons, Volume.Millilitres.ToUSTeaspoons },
						{ AppResources.USTablespoons, Volume.Millilitres.ToUSTablespoons },
						{ AppResources.USQuarts, Volume.Millilitres.ToUSQuarts },
						{ AppResources.USPints, Volume.Millilitres.ToUSPints },
						{ AppResources.USGallons, Volume.Millilitres.ToUSGallons },
						{ AppResources.USFluidOunces, Volume.Millilitres.ToUSFluidOunces },
						{ AppResources.USCups, Volume.Millilitres.ToUSCups },
						{ AppResources.CubicMetres, Volume.Millilitres.ToCubicMetres },
						{ AppResources.CubicFeet, Volume.Millilitres.ToCubicFeet },
						{ AppResources.CubicInches, Volume.Millilitres.ToCubicInches },
						{ AppResources.OilBarrels, Volume.Millilitres.ToOilBarrels },
					}
				},
				{
					AppResources.OilBarrels, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Millilitres, Volume.OilBarrels.ToMillilitres },
						{ AppResources.Litres, Volume.OilBarrels.ToLitres },
						{ AppResources.Kilolitres, Volume.OilBarrels.ToKilolitres },
						{ AppResources.Teaspoons, Volume.OilBarrels.ToTeaspoons },
						{ AppResources.Tablespoons, Volume.OilBarrels.ToTablespoons },
						{ AppResources.Quarts, Volume.OilBarrels.ToQuarts },
						{ AppResources.Pints, Volume.OilBarrels.ToPints },
						{ AppResources.Gallons, Volume.OilBarrels.ToGallons },
						{ AppResources.FluidOunces, Volume.OilBarrels.ToFluidOunces },
						{ AppResources.USTeaspoons, Volume.OilBarrels.ToUSTeaspoons },
						{ AppResources.USTablespoons, Volume.OilBarrels.ToUSTablespoons },
						{ AppResources.USQuarts, Volume.OilBarrels.ToUSQuarts },
						{ AppResources.USPints, Volume.OilBarrels.ToUSPints },
						{ AppResources.USGallons, Volume.OilBarrels.ToUSGallons },
						{ AppResources.USFluidOunces, Volume.OilBarrels.ToUSFluidOunces },
						{ AppResources.USCups, Volume.OilBarrels.ToUSCups },
						{ AppResources.CubicMetres, Volume.OilBarrels.ToCubicMetres },
						{ AppResources.CubicFeet, Volume.OilBarrels.ToCubicFeet },
						{ AppResources.CubicInches, Volume.OilBarrels.ToCubicInches },
					}
				},
				{
					AppResources.Pints, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Millilitres, Volume.Pints.ToMillilitres },
						{ AppResources.Litres, Volume.Pints.ToLitres },
						{ AppResources.Kilolitres, Volume.Pints.ToKilolitres },
						{ AppResources.Teaspoons, Volume.Pints.ToTeaspoons },
						{ AppResources.Tablespoons, Volume.Pints.ToTablespoons },
						{ AppResources.Quarts, Volume.Pints.ToQuarts },
						{ AppResources.Gallons, Volume.Pints.ToGallons },
						{ AppResources.FluidOunces, Volume.Pints.ToFluidOunces },
						{ AppResources.USTeaspoons, Volume.Pints.ToUSTeaspoons },
						{ AppResources.USTablespoons, Volume.Pints.ToUSTablespoons },
						{ AppResources.USQuarts, Volume.Pints.ToUSQuarts },
						{ AppResources.USPints, Volume.Pints.ToUSPints },
						{ AppResources.USGallons, Volume.Pints.ToUSGallons },
						{ AppResources.USFluidOunces, Volume.Pints.ToUSFluidOunces },
						{ AppResources.USCups, Volume.Pints.ToUSCups },
						{ AppResources.CubicMetres, Volume.Pints.ToCubicMetres },
						{ AppResources.CubicFeet, Volume.Pints.ToCubicFeet },
						{ AppResources.CubicInches, Volume.Pints.ToCubicInches },
						{ AppResources.OilBarrels, Volume.Pints.ToOilBarrels },
					}
				},
				{
					AppResources.Quarts, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Millilitres, Volume.Quarts.ToMillilitres },
						{ AppResources.Litres, Volume.Quarts.ToLitres },
						{ AppResources.Kilolitres, Volume.Quarts.ToKilolitres },
						{ AppResources.Teaspoons, Volume.Quarts.ToTeaspoons },
						{ AppResources.Tablespoons, Volume.Quarts.ToTablespoons },
						{ AppResources.Pints, Volume.Quarts.ToPints },
						{ AppResources.Gallons, Volume.Quarts.ToGallons },
						{ AppResources.FluidOunces, Volume.Quarts.ToFluidOunces },
						{ AppResources.USTeaspoons, Volume.Quarts.ToUSTeaspoons },
						{ AppResources.USTablespoons, Volume.Quarts.ToUSTablespoons },
						{ AppResources.USQuarts, Volume.Quarts.ToUSQuarts },
						{ AppResources.USPints, Volume.Quarts.ToUSPints },
						{ AppResources.USGallons, Volume.Quarts.ToUSGallons },
						{ AppResources.USFluidOunces, Volume.Quarts.ToUSFluidOunces },
						{ AppResources.USCups, Volume.Quarts.ToUSCups },
						{ AppResources.CubicMetres, Volume.Quarts.ToCubicMetres },
						{ AppResources.CubicFeet, Volume.Quarts.ToCubicFeet },
						{ AppResources.CubicInches, Volume.Quarts.ToCubicInches },
						{ AppResources.OilBarrels, Volume.Quarts.ToOilBarrels },
					}
				},
				{
					AppResources.Tablespoons, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Millilitres, Volume.Tablespoons.ToMillilitres },
						{ AppResources.Litres, Volume.Tablespoons.ToLitres },
						{ AppResources.Kilolitres, Volume.Tablespoons.ToKilolitres },
						{ AppResources.Teaspoons, Volume.Tablespoons.ToTeaspoons },
						{ AppResources.Quarts, Volume.Tablespoons.ToQuarts },
						{ AppResources.Pints, Volume.Tablespoons.ToPints },
						{ AppResources.Gallons, Volume.Tablespoons.ToGallons },
						{ AppResources.FluidOunces, Volume.Tablespoons.ToFluidOunces },
						{ AppResources.USTeaspoons, Volume.Tablespoons.ToUSTeaspoons },
						{ AppResources.USTablespoons, Volume.Tablespoons.ToUSTablespoons },
						{ AppResources.USQuarts, Volume.Tablespoons.ToUSQuarts },
						{ AppResources.USPints, Volume.Tablespoons.ToUSPints },
						{ AppResources.USGallons, Volume.Tablespoons.ToUSGallons },
						{ AppResources.USFluidOunces, Volume.Tablespoons.ToUSFluidOunces },
						{ AppResources.USCups, Volume.Tablespoons.ToUSCups },
						{ AppResources.CubicMetres, Volume.Tablespoons.ToCubicMetres },
						{ AppResources.CubicFeet, Volume.Tablespoons.ToCubicFeet },
						{ AppResources.CubicInches, Volume.Tablespoons.ToCubicInches },
						{ AppResources.OilBarrels, Volume.Tablespoons.ToOilBarrels },
					}
				},
				{
					AppResources.Teaspoons, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Millilitres, Volume.Teaspoons.ToMillilitres },
						{ AppResources.Litres, Volume.Teaspoons.ToLitres },
						{ AppResources.Kilolitres, Volume.Teaspoons.ToKilolitres },
						{ AppResources.Tablespoons, Volume.Teaspoons.ToTablespoons },
						{ AppResources.Quarts, Volume.Teaspoons.ToQuarts },
						{ AppResources.Pints, Volume.Teaspoons.ToPints },
						{ AppResources.Gallons, Volume.Teaspoons.ToGallons },
						{ AppResources.FluidOunces, Volume.Teaspoons.ToFluidOunces },
						{ AppResources.USTeaspoons, Volume.Teaspoons.ToUSTeaspoons },
						{ AppResources.USTablespoons, Volume.Teaspoons.ToUSTablespoons },
						{ AppResources.USQuarts, Volume.Teaspoons.ToUSQuarts },
						{ AppResources.USPints, Volume.Teaspoons.ToUSPints },
						{ AppResources.USGallons, Volume.Teaspoons.ToUSGallons },
						{ AppResources.USFluidOunces, Volume.Teaspoons.ToUSFluidOunces },
						{ AppResources.USCups, Volume.Teaspoons.ToUSCups },
						{ AppResources.CubicMetres, Volume.Teaspoons.ToCubicMetres },
						{ AppResources.CubicFeet, Volume.Teaspoons.ToCubicFeet },
						{ AppResources.CubicInches, Volume.Teaspoons.ToCubicInches },
						{ AppResources.OilBarrels, Volume.Teaspoons.ToOilBarrels },
					}
				},
				{
					AppResources.USCups, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Millilitres, Volume.USCups.ToMillilitres },
						{ AppResources.Litres, Volume.USCups.ToLitres },
						{ AppResources.Kilolitres, Volume.USCups.ToKilolitres },
						{ AppResources.Teaspoons, Volume.USCups.ToTeaspoons },
						{ AppResources.Tablespoons, Volume.USCups.ToTablespoons },
						{ AppResources.Quarts, Volume.USCups.ToQuarts },
						{ AppResources.Pints, Volume.USCups.ToPints },
						{ AppResources.Gallons, Volume.USCups.ToGallons },
						{ AppResources.FluidOunces, Volume.USCups.ToFluidOunces },
						{ AppResources.USTeaspoons, Volume.USCups.ToUSTeaspoons },
						{ AppResources.USTablespoons, Volume.USCups.ToUSTablespoons },
						{ AppResources.USQuarts, Volume.USCups.ToUSQuarts },
						{ AppResources.USPints, Volume.USCups.ToUSPints },
						{ AppResources.USGallons, Volume.USCups.ToUSGallons },
						{ AppResources.USFluidOunces, Volume.USCups.ToUSFluidOunces },
						{ AppResources.CubicMetres, Volume.USCups.ToCubicMetres },
						{ AppResources.CubicFeet, Volume.USCups.ToCubicFeet },
						{ AppResources.CubicInches, Volume.USCups.ToCubicInches },
						{ AppResources.OilBarrels, Volume.USCups.ToOilBarrels },
					}
				},
				{
					AppResources.USFluidOunces, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Millilitres, Volume.USFluidOunces.ToMillilitres },
						{ AppResources.Litres, Volume.USFluidOunces.ToLitres },
						{ AppResources.Kilolitres, Volume.USFluidOunces.ToKilolitres },
						{ AppResources.Teaspoons, Volume.USFluidOunces.ToTeaspoons },
						{ AppResources.Tablespoons, Volume.USFluidOunces.ToTablespoons },
						{ AppResources.Quarts, Volume.USFluidOunces.ToQuarts },
						{ AppResources.Pints, Volume.USFluidOunces.ToPints },
						{ AppResources.Gallons, Volume.USFluidOunces.ToGallons },
						{ AppResources.FluidOunces, Volume.USFluidOunces.ToFluidOunces },
						{ AppResources.USTeaspoons, Volume.USFluidOunces.ToUSTeaspoons },
						{ AppResources.USTablespoons, Volume.USFluidOunces.ToUSTablespoons },
						{ AppResources.USQuarts, Volume.USFluidOunces.ToUSQuarts },
						{ AppResources.USPints, Volume.USFluidOunces.ToUSPints },
						{ AppResources.USGallons, Volume.USFluidOunces.ToUSGallons },
						{ AppResources.USCups, Volume.USFluidOunces.ToUSCups },
						{ AppResources.CubicMetres, Volume.USFluidOunces.ToCubicMetres },
						{ AppResources.CubicFeet, Volume.USFluidOunces.ToCubicFeet },
						{ AppResources.CubicInches, Volume.USFluidOunces.ToCubicInches },
						{ AppResources.OilBarrels, Volume.USFluidOunces.ToOilBarrels },
					}
				},
				{
					AppResources.USGallons, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Millilitres, Volume.USGallons.ToMillilitres },
						{ AppResources.Litres, Volume.USGallons.ToLitres },
						{ AppResources.Kilolitres, Volume.USGallons.ToKilolitres },
						{ AppResources.Teaspoons, Volume.USGallons.ToTeaspoons },
						{ AppResources.Tablespoons, Volume.USGallons.ToTablespoons },
						{ AppResources.Quarts, Volume.USGallons.ToQuarts },
						{ AppResources.Pints, Volume.USGallons.ToPints },
						{ AppResources.Gallons, Volume.USGallons.ToGallons },
						{ AppResources.FluidOunces, Volume.USGallons.ToFluidOunces },
						{ AppResources.USTeaspoons, Volume.USGallons.ToUSTeaspoons },
						{ AppResources.USTablespoons, Volume.USGallons.ToUSTablespoons },
						{ AppResources.USQuarts, Volume.USGallons.ToUSQuarts },
						{ AppResources.USPints, Volume.USGallons.ToUSPints },
						{ AppResources.USFluidOunces, Volume.USGallons.ToUSFluidOunces },
						{ AppResources.USCups, Volume.USGallons.ToUSCups },
						{ AppResources.CubicMetres, Volume.USGallons.ToCubicMetres },
						{ AppResources.CubicFeet, Volume.USGallons.ToCubicFeet },
						{ AppResources.CubicInches, Volume.USGallons.ToCubicInches },
						{ AppResources.OilBarrels, Volume.USGallons.ToOilBarrels },
					}
				},
				{
					AppResources.USPints, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Millilitres, Volume.USPints.ToMillilitres },
						{ AppResources.Litres, Volume.USPints.ToLitres },
						{ AppResources.Kilolitres, Volume.USPints.ToKilolitres },
						{ AppResources.Teaspoons, Volume.USPints.ToTeaspoons },
						{ AppResources.Tablespoons, Volume.USPints.ToTablespoons },
						{ AppResources.Quarts, Volume.USPints.ToQuarts },
						{ AppResources.Pints, Volume.USPints.ToPints },
						{ AppResources.Gallons, Volume.USPints.ToGallons },
						{ AppResources.FluidOunces, Volume.USPints.ToFluidOunces },
						{ AppResources.USTeaspoons, Volume.USPints.ToUSTeaspoons },
						{ AppResources.USTablespoons, Volume.USPints.ToUSTablespoons },
						{ AppResources.USQuarts, Volume.USPints.ToUSQuarts },
						{ AppResources.USGallons, Volume.USPints.ToUSGallons },
						{ AppResources.USFluidOunces, Volume.USPints.ToUSFluidOunces },
						{ AppResources.USCups, Volume.USPints.ToUSCups },
						{ AppResources.CubicMetres, Volume.USPints.ToCubicMetres },
						{ AppResources.CubicFeet, Volume.USPints.ToCubicFeet },
						{ AppResources.CubicInches, Volume.USPints.ToCubicInches },
						{ AppResources.OilBarrels, Volume.USPints.ToOilBarrels },
					}
				},
				{
					AppResources.USQuarts, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Millilitres, Volume.USQuarts.ToMillilitres },
						{ AppResources.Litres, Volume.USQuarts.ToLitres },
						{ AppResources.Kilolitres, Volume.USQuarts.ToKilolitres },
						{ AppResources.Teaspoons, Volume.USQuarts.ToTeaspoons },
						{ AppResources.Tablespoons, Volume.USQuarts.ToTablespoons },
						{ AppResources.Quarts, Volume.USQuarts.ToQuarts },
						{ AppResources.Pints, Volume.USQuarts.ToPints },
						{ AppResources.Gallons, Volume.USQuarts.ToGallons },
						{ AppResources.FluidOunces, Volume.USQuarts.ToFluidOunces },
						{ AppResources.USTeaspoons, Volume.USQuarts.ToUSTeaspoons },
						{ AppResources.USTablespoons, Volume.USQuarts.ToUSTablespoons },
						{ AppResources.USPints, Volume.USQuarts.ToUSPints },
						{ AppResources.USGallons, Volume.USQuarts.ToUSGallons },
						{ AppResources.USFluidOunces, Volume.USQuarts.ToUSFluidOunces },
						{ AppResources.USCups, Volume.USQuarts.ToUSCups },
						{ AppResources.CubicMetres, Volume.USQuarts.ToCubicMetres },
						{ AppResources.CubicFeet, Volume.USQuarts.ToCubicFeet },
						{ AppResources.CubicInches, Volume.USQuarts.ToCubicInches },
						{ AppResources.OilBarrels, Volume.USQuarts.ToOilBarrels },
					}
				},
				{
					AppResources.USTablespoons, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Millilitres, Volume.USTablespoons.ToMillilitres },
						{ AppResources.Litres, Volume.USTablespoons.ToLitres },
						{ AppResources.Kilolitres, Volume.USTablespoons.ToKilolitres },
						{ AppResources.Teaspoons, Volume.USTablespoons.ToTeaspoons },
						{ AppResources.Tablespoons, Volume.USTablespoons.ToTablespoons },
						{ AppResources.Quarts, Volume.USTablespoons.ToQuarts },
						{ AppResources.Pints, Volume.USTablespoons.ToPints },
						{ AppResources.Gallons, Volume.USTablespoons.ToGallons },
						{ AppResources.FluidOunces, Volume.USTablespoons.ToFluidOunces },
						{ AppResources.USTeaspoons, Volume.USTablespoons.ToUSTeaspoons },
						{ AppResources.USQuarts, Volume.USTablespoons.ToUSQuarts },
						{ AppResources.USPints, Volume.USTablespoons.ToUSPints },
						{ AppResources.USGallons, Volume.USTablespoons.ToUSGallons },
						{ AppResources.USFluidOunces, Volume.USTablespoons.ToUSFluidOunces },
						{ AppResources.USCups, Volume.USTablespoons.ToUSCups },
						{ AppResources.CubicMetres, Volume.USTablespoons.ToCubicMetres },
						{ AppResources.CubicFeet, Volume.USTablespoons.ToCubicFeet },
						{ AppResources.CubicInches, Volume.USTablespoons.ToCubicInches },
						{ AppResources.OilBarrels, Volume.USTablespoons.ToOilBarrels },
					}
				},
				{
					AppResources.USTeaspoons, new Dictionary<string, Func<double, double>>
					{
						{ AppResources.Millilitres, Volume.USTeaspoons.ToMillilitres },
						{ AppResources.Litres, Volume.USTeaspoons.ToLitres },
						{ AppResources.Kilolitres, Volume.USTeaspoons.ToKilolitres },
						{ AppResources.Teaspoons, Volume.USTeaspoons.ToTeaspoons },
						{ AppResources.Tablespoons, Volume.USTeaspoons.ToTablespoons },
						{ AppResources.Quarts, Volume.USTeaspoons.ToQuarts },
						{ AppResources.Pints, Volume.USTeaspoons.ToPints },
						{ AppResources.Gallons, Volume.USTeaspoons.ToGallons },
						{ AppResources.FluidOunces, Volume.USTeaspoons.ToFluidOunces },
						{ AppResources.USTablespoons, Volume.USTeaspoons.ToUSTablespoons },
						{ AppResources.USQuarts, Volume.USTeaspoons.ToUSQuarts },
						{ AppResources.USPints, Volume.USTeaspoons.ToUSPints },
						{ AppResources.USGallons, Volume.USTeaspoons.ToUSGallons },
						{ AppResources.USFluidOunces, Volume.USTeaspoons.ToUSFluidOunces },
						{ AppResources.USCups, Volume.USTeaspoons.ToUSCups },
						{ AppResources.CubicMetres, Volume.USTeaspoons.ToCubicMetres },
						{ AppResources.CubicFeet, Volume.USTeaspoons.ToCubicFeet },
						{ AppResources.CubicInches, Volume.USTeaspoons.ToCubicInches },
						{ AppResources.OilBarrels, Volume.USTeaspoons.ToOilBarrels },
					}
				}
			};
		}

		public Dictionary<string, Dictionary<string, Func<double, double>>> Converters { get; }
	}
}
