//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PutridParrot.UnitsApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PutridParrot.MyUnitConversionApi.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acre.
        /// </summary>
        internal static string Acres {
            get {
                return ResourceManager.GetString("Acres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ampere-turn.
        /// </summary>
        internal static string Ampereturns {
            get {
                return ResourceManager.GetString("Ampereturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        internal static string Angle {
            get {
                return ResourceManager.GetString("Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Unit Conversion.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atmosphere.
        /// </summary>
        internal static string Atmospheres {
            get {
                return ResourceManager.GetString("Atmospheres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar.
        /// </summary>
        internal static string Bars {
            get {
                return ResourceManager.GetString("Bars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bits.
        /// </summary>
        internal static string Bits {
            get {
                return ResourceManager.GetString("Bits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bits per second.
        /// </summary>
        internal static string BitsPerSecond {
            get {
                return ResourceManager.GetString("BitsPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to British Thermal Units.
        /// </summary>
        internal static string Btu {
            get {
                return ResourceManager.GetString("Btu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gram calorie.
        /// </summary>
        internal static string Calories {
            get {
                return ResourceManager.GetString("Calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carats.
        /// </summary>
        internal static string Carats {
            get {
                return ResourceManager.GetString("Carats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celsius.
        /// </summary>
        internal static string Celsius {
            get {
                return ResourceManager.GetString("Celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centimetres.
        /// </summary>
        internal static string Centimetres {
            get {
                return ResourceManager.GetString("Centimetres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centuries.
        /// </summary>
        internal static string Centuries {
            get {
                return ResourceManager.GetString("Centuries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        internal static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of converters.
        /// </summary>
        internal static string ConverterList {
            get {
                return ResourceManager.GetString("ConverterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic Feet.
        /// </summary>
        internal static string CubicFeet {
            get {
                return ResourceManager.GetString("CubicFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic Inches.
        /// </summary>
        internal static string CubicInches {
            get {
                return ResourceManager.GetString("CubicInches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic Metres.
        /// </summary>
        internal static string CubicMetres {
            get {
                return ResourceManager.GetString("CubicMetres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Storage.
        /// </summary>
        internal static string DataStorage {
            get {
                return ResourceManager.GetString("DataStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Transfer Rate.
        /// </summary>
        internal static string DataTransferRate {
            get {
                return ResourceManager.GetString("DataTransferRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decades.
        /// </summary>
        internal static string Decades {
            get {
                return ResourceManager.GetString("Decades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degrees.
        /// </summary>
        internal static string Degrees {
            get {
                return ResourceManager.GetString("Degrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynes.
        /// </summary>
        internal static string Dynes {
            get {
                return ResourceManager.GetString("Dynes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronvolts.
        /// </summary>
        internal static string Electronvolts {
            get {
                return ResourceManager.GetString("Electronvolts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        internal static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fahrenheit.
        /// </summary>
        internal static string Fahrenheit {
            get {
                return ResourceManager.GetString("Fahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        internal static string Feet {
            get {
                return ResourceManager.GetString("Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet per second.
        /// </summary>
        internal static string FeetPerSecond {
            get {
                return ResourceManager.GetString("FeetPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluid Ounces.
        /// </summary>
        internal static string FluidOunces {
            get {
                return ResourceManager.GetString("FluidOunces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foot Pounds.
        /// </summary>
        internal static string FootPounds {
            get {
                return ResourceManager.GetString("FootPounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force.
        /// </summary>
        internal static string Force {
            get {
                return ResourceManager.GetString("Force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Economy.
        /// </summary>
        internal static string FuelEconomy {
            get {
                return ResourceManager.GetString("FuelEconomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallons.
        /// </summary>
        internal static string Gallons {
            get {
                return ResourceManager.GetString("Gallons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gigabits.
        /// </summary>
        internal static string Gigabits {
            get {
                return ResourceManager.GetString("Gigabits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gigabits per second.
        /// </summary>
        internal static string GigaBitsPerSecond {
            get {
                return ResourceManager.GetString("GigaBitsPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gigabytes.
        /// </summary>
        internal static string Gigabytes {
            get {
                return ResourceManager.GetString("Gigabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gigabytes per second.
        /// </summary>
        internal static string GigaBytesPerSecond {
            get {
                return ResourceManager.GetString("GigaBytesPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gigahertz.
        /// </summary>
        internal static string Gigahertz {
            get {
                return ResourceManager.GetString("Gigahertz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gilbert.
        /// </summary>
        internal static string Gilberts {
            get {
                return ResourceManager.GetString("Gilberts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradians.
        /// </summary>
        internal static string Gradians {
            get {
                return ResourceManager.GetString("Gradians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grams.
        /// </summary>
        internal static string Grams {
            get {
                return ResourceManager.GetString("Grams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        internal static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hectare.
        /// </summary>
        internal static string Hectares {
            get {
                return ResourceManager.GetString("Hectares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hertz.
        /// </summary>
        internal static string Hertz {
            get {
                return ResourceManager.GetString("Hertz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inches.
        /// </summary>
        internal static string Inches {
            get {
                return ResourceManager.GetString("Inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joules.
        /// </summary>
        internal static string Joules {
            get {
                return ResourceManager.GetString("Joules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelvin.
        /// </summary>
        internal static string Kelvin {
            get {
                return ResourceManager.GetString("Kelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kibibits.
        /// </summary>
        internal static string Kibibits {
            get {
                return ResourceManager.GetString("Kibibits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kibibits per second.
        /// </summary>
        internal static string KibibitsPerSecond {
            get {
                return ResourceManager.GetString("KibibitsPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilobits.
        /// </summary>
        internal static string Kilobits {
            get {
                return ResourceManager.GetString("Kilobits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilobits per second.
        /// </summary>
        internal static string KiloBitsPerSecond {
            get {
                return ResourceManager.GetString("KiloBitsPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilobytes.
        /// </summary>
        internal static string Kilobytes {
            get {
                return ResourceManager.GetString("Kilobytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilobytes per second.
        /// </summary>
        internal static string KiloBytesPerSecond {
            get {
                return ResourceManager.GetString("KiloBytesPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilocalories.
        /// </summary>
        internal static string Kilocalories {
            get {
                return ResourceManager.GetString("Kilocalories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilogramforce.
        /// </summary>
        internal static string Kilogramforce {
            get {
                return ResourceManager.GetString("Kilogramforce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilograms.
        /// </summary>
        internal static string Kilograms {
            get {
                return ResourceManager.GetString("Kilograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilohertz.
        /// </summary>
        internal static string Kilohertz {
            get {
                return ResourceManager.GetString("Kilohertz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilojoules.
        /// </summary>
        internal static string Kilojoules {
            get {
                return ResourceManager.GetString("Kilojoules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilolitres.
        /// </summary>
        internal static string Kilolitres {
            get {
                return ResourceManager.GetString("Kilolitres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometre per litre.
        /// </summary>
        internal static string KilometrePerLitre {
            get {
                return ResourceManager.GetString("KilometrePerLitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometres.
        /// </summary>
        internal static string Kilometres {
            get {
                return ResourceManager.GetString("Kilometres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometres per hour.
        /// </summary>
        internal static string KilometresPerHour {
            get {
                return ResourceManager.GetString("KilometresPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilowatt Hours.
        /// </summary>
        internal static string KilowattHours {
            get {
                return ResourceManager.GetString("KilowattHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knots.
        /// </summary>
        internal static string Knots {
            get {
                return ResourceManager.GetString("Knots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length / Distance.
        /// </summary>
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Litres.
        /// </summary>
        internal static string Litres {
            get {
                return ResourceManager.GetString("Litres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Litres per 100 Kilometres.
        /// </summary>
        internal static string LitresPer100Kilometres {
            get {
                return ResourceManager.GetString("LitresPer100Kilometres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lumen Hour.
        /// </summary>
        internal static string LumenHour {
            get {
                return ResourceManager.GetString("LumenHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lumen Minute.
        /// </summary>
        internal static string LumenMinute {
            get {
                return ResourceManager.GetString("LumenMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lumen Second.
        /// </summary>
        internal static string LumenSecond {
            get {
                return ResourceManager.GetString("LumenSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luminous Energy.
        /// </summary>
        internal static string LuminousEnergy {
            get {
                return ResourceManager.GetString("LuminousEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnetomotive Force.
        /// </summary>
        internal static string MagnetomotiveForce {
            get {
                return ResourceManager.GetString("MagnetomotiveForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass / Weight.
        /// </summary>
        internal static string Mass {
            get {
                return ResourceManager.GetString("Mass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mebibits.
        /// </summary>
        internal static string Mebibits {
            get {
                return ResourceManager.GetString("Mebibits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mebibit per second.
        /// </summary>
        internal static string MebibitsPerSecond {
            get {
                return ResourceManager.GetString("MebibitsPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanical Horse Power.
        /// </summary>
        internal static string MechanicalHorsePower {
            get {
                return ResourceManager.GetString("MechanicalHorsePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megabits.
        /// </summary>
        internal static string Megabits {
            get {
                return ResourceManager.GetString("Megabits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megabits per second.
        /// </summary>
        internal static string MegaBitsPerSecond {
            get {
                return ResourceManager.GetString("MegaBitsPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megabytes.
        /// </summary>
        internal static string Megabytes {
            get {
                return ResourceManager.GetString("Megabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megabytes per second.
        /// </summary>
        internal static string MegaBytesPerSecond {
            get {
                return ResourceManager.GetString("MegaBytesPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megahertz.
        /// </summary>
        internal static string Megahertz {
            get {
                return ResourceManager.GetString("Megahertz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metres.
        /// </summary>
        internal static string Metres {
            get {
                return ResourceManager.GetString("Metres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metres per second.
        /// </summary>
        internal static string MetresPerSecond {
            get {
                return ResourceManager.GetString("MetresPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric Horse Power.
        /// </summary>
        internal static string MetricHorsePower {
            get {
                return ResourceManager.GetString("MetricHorsePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microseconds.
        /// </summary>
        internal static string Microseconds {
            get {
                return ResourceManager.GetString("Microseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles.
        /// </summary>
        internal static string Miles {
            get {
                return ResourceManager.GetString("Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles per gallon.
        /// </summary>
        internal static string MilesPerGallon {
            get {
                return ResourceManager.GetString("MilesPerGallon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles per hour.
        /// </summary>
        internal static string MilesPerHour {
            get {
                return ResourceManager.GetString("MilesPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milligrams.
        /// </summary>
        internal static string Milligrams {
            get {
                return ResourceManager.GetString("Milligrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millilitres.
        /// </summary>
        internal static string Millilitres {
            get {
                return ResourceManager.GetString("Millilitres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millimetres.
        /// </summary>
        internal static string Millimetres {
            get {
                return ResourceManager.GetString("Millimetres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliradians.
        /// </summary>
        internal static string Milliradians {
            get {
                return ResourceManager.GetString("Milliradians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliseconds.
        /// </summary>
        internal static string Milliseconds {
            get {
                return ResourceManager.GetString("Milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute of arc.
        /// </summary>
        internal static string MinuteOfArc {
            get {
                return ResourceManager.GetString("MinuteOfArc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        internal static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nanoseconds.
        /// </summary>
        internal static string Nanoseconds {
            get {
                return ResourceManager.GetString("Nanoseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nautical Miles.
        /// </summary>
        internal static string NauticalMiles {
            get {
                return ResourceManager.GetString("NauticalMiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newtons.
        /// </summary>
        internal static string Newtons {
            get {
                return ResourceManager.GetString("Newtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil Barrels.
        /// </summary>
        internal static string OilBarrels {
            get {
                return ResourceManager.GetString("OilBarrels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ounces.
        /// </summary>
        internal static string Ounces {
            get {
                return ResourceManager.GetString("Ounces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pascal.
        /// </summary>
        internal static string Pascals {
            get {
                return ResourceManager.GetString("Pascals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pints.
        /// </summary>
        internal static string Pints {
            get {
                return ResourceManager.GetString("Pints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poundals.
        /// </summary>
        internal static string Poundals {
            get {
                return ResourceManager.GetString("Poundals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pounds.
        /// </summary>
        internal static string Pounds {
            get {
                return ResourceManager.GetString("Pounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        internal static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        internal static string Pressure {
            get {
                return ResourceManager.GetString("Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psi.
        /// </summary>
        internal static string Psi {
            get {
                return ResourceManager.GetString("Psi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarts.
        /// </summary>
        internal static string Quarts {
            get {
                return ResourceManager.GetString("Quarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radians.
        /// </summary>
        internal static string Radians {
            get {
                return ResourceManager.GetString("Radians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rankine.
        /// </summary>
        internal static string Rankine {
            get {
                return ResourceManager.GetString("Rankine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds of arc.
        /// </summary>
        internal static string SecondsOfArc {
            get {
                return ResourceManager.GetString("SecondsOfArc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Unit.
        /// </summary>
        internal static string SelectUnit {
            get {
                return ResourceManager.GetString("SelectUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square Feet.
        /// </summary>
        internal static string SquareFeet {
            get {
                return ResourceManager.GetString("SquareFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square Inch.
        /// </summary>
        internal static string SquareInches {
            get {
                return ResourceManager.GetString("SquareInches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square Kilometre.
        /// </summary>
        internal static string SquareKilometres {
            get {
                return ResourceManager.GetString("SquareKilometres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square Metre.
        /// </summary>
        internal static string SquareMetres {
            get {
                return ResourceManager.GetString("SquareMetres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square Mile.
        /// </summary>
        internal static string SquareMiles {
            get {
                return ResourceManager.GetString("SquareMiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square Yard.
        /// </summary>
        internal static string SquareYards {
            get {
                return ResourceManager.GetString("SquareYards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stones.
        /// </summary>
        internal static string Stones {
            get {
                return ResourceManager.GetString("Stones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablespoons.
        /// </summary>
        internal static string Tablespoons {
            get {
                return ResourceManager.GetString("Tablespoons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talbot.
        /// </summary>
        internal static string Talbot {
            get {
                return ResourceManager.GetString("Talbot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaspoons.
        /// </summary>
        internal static string Teaspoons {
            get {
                return ResourceManager.GetString("Teaspoons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terabits.
        /// </summary>
        internal static string Terabits {
            get {
                return ResourceManager.GetString("Terabits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terabits per second.
        /// </summary>
        internal static string TeraBitsPerSecond {
            get {
                return ResourceManager.GetString("TeraBitsPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terabytes.
        /// </summary>
        internal static string Terabytes {
            get {
                return ResourceManager.GetString("Terabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terabytes per second.
        /// </summary>
        internal static string TeraBytesPerSecond {
            get {
                return ResourceManager.GetString("TeraBytesPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonnes.
        /// </summary>
        internal static string Tonnes {
            get {
                return ResourceManager.GetString("Tonnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torr.
        /// </summary>
        internal static string Torrs {
            get {
                return ResourceManager.GetString("Torrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Cups.
        /// </summary>
        internal static string USCups {
            get {
                return ResourceManager.GetString("USCups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Fluid Ounces.
        /// </summary>
        internal static string USFluidOunces {
            get {
                return ResourceManager.GetString("USFluidOunces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Gallons.
        /// </summary>
        internal static string USGallons {
            get {
                return ResourceManager.GetString("USGallons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Miles per gallon.
        /// </summary>
        internal static string USMilesPerGallon {
            get {
                return ResourceManager.GetString("USMilesPerGallon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Pints.
        /// </summary>
        internal static string USPints {
            get {
                return ResourceManager.GetString("USPints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Quarts.
        /// </summary>
        internal static string USQuarts {
            get {
                return ResourceManager.GetString("USQuarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Tablespoons.
        /// </summary>
        internal static string USTablespoons {
            get {
                return ResourceManager.GetString("USTablespoons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Teaspoons.
        /// </summary>
        internal static string USTeaspoons {
            get {
                return ResourceManager.GetString("USTeaspoons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US therm.
        /// </summary>
        internal static string USTherms {
            get {
                return ResourceManager.GetString("USTherms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watt Hours.
        /// </summary>
        internal static string WattHours {
            get {
                return ResourceManager.GetString("WattHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weeks.
        /// </summary>
        internal static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yards.
        /// </summary>
        internal static string Yards {
            get {
                return ResourceManager.GetString("Yards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        internal static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
