name: Build PutridParrot.UnitsApi

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Manual Run

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test PutridParrot.UnitsApi.Tests/PutridParrot.UnitsApi.Tests.csproj --no-restore --verbosity normal
    - name: Create Package
      run: dotnet pack --configuration Release
#    - name: Create Artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: PutridParrot.UnitsApi
#        path: /home/runner/work/PutridParrot.UnitsApi/PutridParrot.UnitsApi/PutridParrot.UnitsApi/bin/Release/PutridParrot.UnitsApi.*.nupkg
#    - name: Publish to Nuget
#      run: dotnet nuget push /home/runner/work/PutridParrot.UnitsApi/PutridParrot.UnitsApi/PutridParrot.UnitsApi/bin/Release/*.nupkg --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
#    - name: Publish to GitHub
#      run: |
#        dotnet nuget add source https://nuget.pkg.github.com/putridparrot/index.json -n github -u putridparrot -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
#        dotnet nuget push /home/runner/work/PutridParrot.UnitsApi/PutridParrot.UnitsApi/PutridParrot.UnitsApi/bin/Release/*.nupkg --skip-duplicate --api-key ${{secrets.GITHUB_TOKEN}} --source "github"
